// Setting the varibales like this will allow you to input via command line or file. Ex: rg_name
variable rg_name {}
variable rg_location {}
variable akc_name {}
variable akc_dns_prefix  {}
variable akc_sys_nodepool_name  {}
variable akc_sys_node_count  {}
variable akc_sys_vm_size  {}
variable akc_tags  {}
variable akc_cnp_name  {}
variable akc_cnp_vm_size  {}
variable akc_cnp_node_count  {}
variable akc_kubernetes_version  {}
variable akc_ssh_key  {}
variable akc_max_pods  {}
variable akc_min_count  {}
variable akc_max_count  {}
variable kv_name  {}
variable kv_soft_delete_retention_days {}
variable kv_sku_name  {}
variable kv_enabled {}
variable slug {}